# http://about.travis-ci.org/docs/user/languages/python/

dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install: 
  - pip install git+git://github.com/danmichaelo/mwtemplates.git

before_script:
  - pip install pytest pytest-pep8 pytest-cov coveralls

script: 
  - py.test -v --pep8 mwtextextractor --cov mwtextextractor --doctest-modules tests.py

after_success:
  - coveralls
